version: "3.8"

services:
  backend:
    build:
      context: ./backend
      target: prod
    env_file:
      # For production, ensure you have a .env file based on .env.production.template
      - ./backend/.env
    working_dir: /app
    ports:
      - "5000:5000"
    # Volumes removed for production, code is baked into the image
    restart: unless-stopped
    # Command removed for production, uses Dockerfile CMD (gunicorn)
    networks:
      - appnet

  frontend:
    build:
      context: ./frontend
      target: prod
    ports:
      - "8000:80"
    # Volumes removed for production, Nginx serves files from the image
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

# =========================
# .env Usage Instructions
# =========================
# Copy backend/.env.example to backend/.env and fill in your values.
# docker-compose will automatically load environment variables from backend/.env for the backend service.
# For production, use backend/.env.production.template as a starting point.

# =========================
# Stripe CLI Webhook Forwarding
# =========================
# To forward Stripe webhooks to your backend in local development, run:
#   stripe listen --forward-to localhost:5000/api/stripe/webhook
# (Requires Stripe CLI: https://stripe.com/docs/stripe-cli)