version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000" # Map host port 5001 to container port 5000
    volumes:
      # Mount backend code for development (optional, remove for production image)
      - ./backend:/app/backend
    env_file:
      - .env # Load environment variables from .env file
    environment:
      # Ensure Flask runs in production mode inside the container unless overridden in .env
      - FLASK_ENV=${FLASK_ENV:-production}
      - PORT=${PORT:-5000}
    restart: unless-stopped

  frontend:
    image: nginx:stable-alpine
    ports:
      - "8080:80" # Map host port 8080 to container port 80
    volumes:
      # Mount the built frontend assets (assuming 'dist' folder)
      - ./frontend/dist:/usr/share/nginx/html
      # Mount the custom nginx configuration
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro # Read-only mount
    depends_on:
      - backend # Ensure backend starts before frontend attempts to connect
    restart: unless-stopped

# Optional: Define networks if needed
# networks:
#   app-network:
#     driver: bridge

# Optional: Define volumes if needed for persistent data (e.g., database)
# volumes:
#   db-data: