version: "3.8"

services:
  backend:
    build:
      context: ./backend
      target: dev
    env_file:
      - ./backend/.env
    working_dir: /app
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    restart: unless-stopped
    command: flask run --host=0.0.0.0 --port=5000
    networks:
      - appnet

  frontend:
    image: node:20-alpine
    working_dir: /app
    ports:
      - "8000:5173"
    volumes:
      - ./frontend:/app
    restart: unless-stopped
    command: npm run dev -- --host
    depends_on:
      - backend
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

# =========================
# .env Usage Instructions
# =========================
# Copy backend/.env.example to backend/.env and fill in your values.
# docker-compose will automatically load environment variables from backend/.env for the backend service.
# For production, use backend/.env.production.template as a starting point.

# =========================
# Stripe CLI Webhook Forwarding
# =========================
# To forward Stripe webhooks to your backend in local development, run:
#   stripe listen --forward-to localhost:5000/api/stripe/webhook
# (Requires Stripe CLI: https://stripe.com/docs/stripe-cli)